version: '3.8'

services:
    financialplanning-api:
        image: financialplanning-api
        build:
            context: ./FinancialPlanningBE
            dockerfile: ./Dockerfile
        environment:
            - DB_SERVER=financialplanning-db.cf84cc04wegh.ap-southeast-1.rds.amazonaws.com
            - DB_PORT=1433
            - DB_NAME=FinancialPlanning
            - DB_USER=admin
            - DB_PASSWORD=pjb-group4
            - SYSADMIN_EMAIL=financialplanapp@gmail.com
            - SYSADMIN_PASSWORD=FinancialPlanningApp123
            - AWS_ACCESSKEY=AKIAW3MEBMWBODMFHXMF
            - AWS_SECRETKEY=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
            - AWS_REGION=ap-southeast-1
            - AWS_BUCKETNAME=financial-planning-pjb
        ports:
            - '5085:5085'

    financialplanning-ui:
        image: financialplanning-ui
        build:
            context: ./FinancialPlaningUI/FinancialPlaning
            dockerfile: ./Dockerfile
        ports:
            - "4200:4000"
