version: '3.8'

services:
  financialplanning-api:
    image: financialplanning-api
    build: 
      context: ./FinancialPlanningBE
      dockerfile: Dockerfile
    environment:
      - ConnectionString__DefaultConnection=Server=sql_server,8020;Database=FinancialPlanning;User ID=sa;Password=aB2n1qrsRvL7rVWHoNsxfwB9;Trusted_Connection=True;TrustServerCertificate=True;
      - SYSADMIN_EMAIL=financialplanapp@gmail.com
      - SYSADMIN_PASSWORD=FinancialPlanningApp123
      - AWS__AccessKey=AKIAW3MEBMWBODMFHXMF
      - AWS__SecretKey=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
      - AWS__Region=ap-southeast-1
      - AWS__BucketName=financial-planning-pjb
    ports:
      - "5085:5085"
    depends_on:
      - sql_server

  financialplanning-ui:
    image: financialplanning-ui
    build: 
      context: ./FinancialPlaningUI/FinancialPlaning
      dockerfile: Dockerfile
    ports:
      - "4200:4000"

  sql_server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    environment:
      - MSSQL_SA_PASSWORD=aB2n1qrsRvL7rVWHoNsxfwB9
      - ACCEPT_EULA=Y
    ports: 
      - "8020:1433"
    

